experiment_type: "utility+privacy" # choices=["utility", "utility+privacy", "compression", "compression+filter"]
beta: 0.2

mine:
  utility_stats_network_model_name: "MINE_Model"
  utility_stats_network_model_params: {in_dim: 129, hidden_dims: [32]}
  privacy_stats_network_model_name: "MINE_Model"
  privacy_stats_network_model_params: {in_dim: 129, hidden_dims: [32]}
  use_prev_epochs_mi_model: false
  mine_batch_size: -1 # -1 means all data
  mine_epochs_privacy: 2000
  mine_epochs_utility: 2000
  utility_stats_network_model_path: null
  privacy_stats_network_model_path: null

log:
  log_dir_path: "lightning_logs"
  log_file_path: "lightning_logs/logs.txt"