experiment:
  dataset_name: sst2  # Default dataset name 
  dataset_path: null
  experiment_type: "utility+privacy" # choices=["utility", "utility+privacy", "compression", "compression+filtering"]
  mine_params:
    utility_stats_network_model_name: "MIModel"
    utility_stats_network_model_params: {in_dim: 768}
    privacy_stats_network_model_name: "MIModel"
    privacy_stats_network_model_params: {in_dim: 768}
    use_prev_epochs_mi_model: true
    mine_batch_size: -1
    mine_epochs_privacy: 2000
    mine_epochs_utility: 2000
    utility_stats_network_model_path: null
    privacy_stats_network_model_path: null
  encoder_params:
    encoder_model_name: "DenseEncoder2"
    encoder_model_params: {in_dim: 768, hidden_dims: [512, 256], out_dim: 128}
    num_enc_epochs: 10
    enc_save_dir_path: null
  log_params:
    log_dir_path: "lightning_logs"
    log_file_path: "lightning_logs/logs.txt"
  beta: 0.2
  combination_type: "premise_only" # choices = ["concat", "join", "premise_only"]

dataset:
  embeddings_path: data/processed