experiment:
  dataset_name: sst2  # Default dataset name
  experiment_type: "utility+privacy"
  mine_params:
    utility_stats_network_model_name: "model_name"
    utility_stats_network_model_params: {}
    privacy_stats_network_model_name: "model_name"
    privacy_stats_network_model_params: {}
    use_prev_epochs_mi_model: true
    mine_batch_size: -1
    mine_epochs_privacy: 2000
    mine_epochs_utility: 2000
    utility_stats_network_model_path: null
    privacy_stats_network_model_path: null
  encoder_params:
    encoder_model_name: "encoder_name"
    encoder_model_params: {}
    num_enc_epochs: 10
    enc_save_dir_path: null
  experiment_date: "2022-01-01"
  beta: 0.2
  combination_type: "premise_only"

